import { defineCollection, z } from "astro:content";

/**
 * POSTS
 * These are the buying guides generated by agents.
 */
const posts = defineCollection({
  type: "content",
  schema: z.object({
    title: z.string(),
    description: z.string(),
    publishedAt: z.coerce.date(),
    category: z.string(),
    audience: z.string(),

    heroImage: z.string(),
    heroAlt: z.string(),
    imageCreditName: z.string().optional(),
    imageCreditUrl: z.string().url().optional(),

    products: z.array(
      z.object({
        title: z.string(),

        // Option B: available now (used later to look up real products)
        amazon_search_query: z.string().optional().nullable(),

        // Real commerce fields (nullable until you have an API)
        url: z.string().url().optional().nullable(),
        price: z.string().optional().nullable(),
        rating: z.number().optional().nullable(),
        reviews_count: z.number().optional().nullable(),

        description: z.string(),
      })
    ),

    // Optional future-proofing
    updatedAt: z.coerce.date().optional(),
  }),
});

/**
 * SITE / TAXONOMY
 * This file is fully agent-owned.
 * The UI reads from it but never encodes knowledge.
 */
const site = defineCollection({
  type: "data",
  schema: z.object({
    brand: z.object({
      name: z.string(),
      tagline: z.string(),
    }),

    groups: z.array(
      z.object({
        key: z.string(),            // e.g. "home", "life"
        label: z.string(),          // e.g. "Home", "Life"
        intro: z.string(),          // used on /posts/[group]
        categories: z.array(z.string()), // maps post.category → group
      })
    ),

    /**
     * Homepage configuration (optional but recommended)
     * Lets agents fully control homepage copy without UI edits.
     */
    homepage: z
      .object({
        seoTitle: z.string(),
        seoDescription: z.string(),

        trustTitle: z.string(),
        trustCards: z.array(
          z.object({
            title: z.string(),
            body: z.string(),
          })
        ),

        ctaTitle: z.string(),
        ctaBody: z.string(),
        ctaInputPlaceholder: z.string(),
        ctaButtonText: z.string(),
      })
      .optional(),
  }),
});

export const collections = {
  posts,
  site,
};
